/* Gives the exact vector-library references (src/port/vu0_a.c, vu0_b.c) the game's own function names for the PC
   build. Generated from the Ref_ prototypes in include/port/ (port/tools/undefined.py lists what is missing). */
#define Ref_ClipPlane_DistArray ClipPlane_DistArray
#define Ref_ClipPlane_EdgeParam ClipPlane_EdgeParam
#define Ref_ClipPoly_ClipPlane ClipPoly_ClipPlane
#define Ref_ClipPoly_ProjectCur ClipPoly_ProjectCur
#define Ref_ClipPoly_ProjectMtx ClipPoly_ProjectMtx
#define Ref_ClipVtx_Copy ClipVtx_Copy
#define Ref_ClipVtx_CopyArray ClipVtx_CopyArray
#define Ref_ClipVtx_Lerp ClipVtx_Lerp
#define Ref_ClipVtx_Set ClipVtx_Set
#define Ref_ClipVtx_SetArray ClipVtx_SetArray
#define Ref_cosf cosf
#define Ref_func_001204B8 func_001204B8
#define Ref_func_00120F00 func_00120F00
#define Ref_IVec3_Add IVec3_Add
#define Ref_IVec3_Clamp IVec3_Clamp
#define Ref_IVec3_Copy IVec3_Copy
#define Ref_IVec3_Div IVec3_Div
#define Ref_IVec3_Mul IVec3_Mul
#define Ref_IVec3_Scale IVec3_Scale
#define Ref_IVec3_Set IVec3_Set
#define Ref_IVec3_Sub IVec3_Sub
#define Ref_IVec4_Add IVec4_Add
#define Ref_IVec4_Clamp IVec4_Clamp
#define Ref_IVec4_Copy IVec4_Copy
#define Ref_IVec4_Div IVec4_Div
#define Ref_IVec4_InGsRange IVec4_InGsRange
#define Ref_IVec4_InGsRange3 IVec4_InGsRange3
#define Ref_IVec4_InGsRange4 IVec4_InGsRange4
#define Ref_IVec4_Mul IVec4_Mul
#define Ref_IVec4_Scale IVec4_Scale
#define Ref_IVec4_Set IVec4_Set
#define Ref_IVec4_SetZero IVec4_SetZero
#define Ref_IVec4_SetZeroW1 IVec4_SetZeroW1
#define Ref_IVec4_Sub IVec4_Sub
#define Ref_IVec4_Swap IVec4_Swap
#define Ref_IVec4_ToFloat IVec4_ToFloat
#define Ref_IVec4_ToFloat12 IVec4_ToFloat12
#define Ref_IVec4_ToFloat4 IVec4_ToFloat4
#define Ref_IVec_Stub IVec_Stub
#define Ref_Mathf_Cos Mathf_Cos
#define Ref_Mathf_Sin Mathf_Sin
#define Ref_Mtx_AxisZToEuler Mtx_AxisZToEuler
#define Ref_Mtx_ClearTrans Mtx_ClearTrans
#define Ref_Mtx_Copy Mtx_Copy
#define Ref_Mtx_GetTrans Mtx_GetTrans
#define Ref_Mtx_InverseRT Mtx_InverseRT
#define Ref_Mtx_MakeCamera Mtx_MakeCamera
#define Ref_Mtx_MakeDropShadow Mtx_MakeDropShadow
#define Ref_Mtx_MakeNormalLight Mtx_MakeNormalLight
#define Ref_Mtx_MakeViewScreen Mtx_MakeViewScreen
#define Ref_Mtx_Mul Mtx_Mul
#define Ref_Mtx_MulVec3 Mtx_MulVec3
#define Ref_Mtx_MulVec4 Mtx_MulVec4
#define Ref_Mtx_ProjectInt Mtx_ProjectInt
#define Ref_Mtx_ProjectPoint Mtx_ProjectPoint
#define Ref_Mtx_ProjectPoints Mtx_ProjectPoints
#define Ref_Mtx_ProjectPointsStq Mtx_ProjectPointsStq
#define Ref_Mtx_ProjectPointStq Mtx_ProjectPointStq
#define Ref_Mtx_RotateX Mtx_RotateX
#define Ref_Mtx_RotateXYZ Mtx_RotateXYZ
#define Ref_Mtx_RotateY Mtx_RotateY
#define Ref_Mtx_RotateZ Mtx_RotateZ
#define Ref_Mtx_RotateZXY Mtx_RotateZXY
#define Ref_Mtx_RotateZXYTranslate Mtx_RotateZXYTranslate
#define Ref_Mtx_ScaleDiag Mtx_ScaleDiag
#define Ref_Mtx_ScaleDiagUniform Mtx_ScaleDiagUniform
#define Ref_Mtx_SetRows Mtx_SetRows
#define Ref_Mtx_SetTrans Mtx_SetTrans
#define Ref_Mtx_StoreIdentity Mtx_StoreIdentity
#define Ref_Mtx_StoreIdentityRot Mtx_StoreIdentityRot
#define Ref_Mtx_Translate Mtx_Translate
#define Ref_Mtx_TranslateLocal Mtx_TranslateLocal
#define Ref_Mtx_Transpose Mtx_Transpose
#define Ref_Rand_Float01_Model Rand_Float01_Model
#define Ref_Rand_Init Rand_Init
#define Ref_Rand_SeedFloat Rand_SeedFloat
#define Ref_sinf sinf
#define Ref_Vec3_Add Vec3_Add
#define Ref_Vec3_Add4 Vec3_Add4
#define Ref_Vec3_AddClamp Vec3_AddClamp
#define Ref_Vec3_AddSub Vec3_AddSub
#define Ref_Vec3_Clamp Vec3_Clamp
#define Ref_Vec3_Copy Vec3_Copy
#define Ref_Vec3_Cross Vec3_Cross
#define Ref_Vec3_DiffToEuler Vec3_DiffToEuler
#define Ref_Vec3_DirToEuler Vec3_DirToEuler
#define Ref_Vec3_Dist Vec3_Dist
#define Ref_Vec3_DistSq Vec3_DistSq
#define Ref_Vec3_Div Vec3_Div
#define Ref_Vec3_Dot Vec3_Dot
#define Ref_Vec3_Length Vec3_Length
#define Ref_Vec3_LengthSq Vec3_LengthSq
#define Ref_Vec3_Lerp Vec3_Lerp
#define Ref_Vec3_Mul Vec3_Mul
#define Ref_Vec3_Normalize Vec3_Normalize
#define Ref_Vec3_RotateAxis Vec3_RotateAxis
#define Ref_Vec3_RotateX Vec3_RotateX
#define Ref_Vec3_RotateY Vec3_RotateY
#define Ref_Vec3_Scale Vec3_Scale
#define Ref_Vec3_ScaleAdd Vec3_ScaleAdd
#define Ref_Vec3_ScaleSub Vec3_ScaleSub
#define Ref_Vec3_Set Vec3_Set
#define Ref_Vec3_Sub Vec3_Sub
#define Ref_Vec3_SubAdd Vec3_SubAdd
#define Ref_Vec4_Add Vec4_Add
#define Ref_Vec4_AddClamp Vec4_AddClamp
#define Ref_Vec4_Clamp Vec4_Clamp
#define Ref_Vec4_Copy Vec4_Copy
#define Ref_Vec4_Div Vec4_Div
#define Ref_Vec4_Lerp Vec4_Lerp
#define Ref_Vec4_Mul Vec4_Mul
#define Ref_Vec4_RotateEuler Vec4_RotateEuler
#define Ref_Vec4_Scale Vec4_Scale
#define Ref_Vec4_Set Vec4_Set
#define Ref_Vec4_SetZero Vec4_SetZero
#define Ref_Vec4_SetZeroW1 Vec4_SetZeroW1
#define Ref_Vec4_Sub Vec4_Sub
#define Ref_Vec4_Swap Vec4_Swap
#define Ref_Vec4_ToFixed12 Vec4_ToFixed12
#define Ref_Vec4_ToFixed4 Vec4_ToFixed4
#define Ref_Vec4_ToFixed4XY Vec4_ToFixed4XY
#define Ref_Vec4_ToInt Vec4_ToInt
#define Ref_Vu0_CheckState Vu0_CheckState
#define Ref_Vu0Clip_LoadMtx Vu0Clip_LoadMtx
#define Ref_Vu0Clip_SetMulMtx Vu0Clip_SetMulMtx
#define Ref_Vu0Clip_StoreMtx Vu0Clip_StoreMtx
#define Ref_Vu0Cur_AxisZToEuler Vu0Cur_AxisZToEuler
#define Ref_Vu0Cur_ClearTrans Vu0Cur_ClearTrans
#define Ref_Vu0Cur_GetStackDepth Vu0Cur_GetStackDepth
#define Ref_Vu0Cur_GetTrans Vu0Cur_GetTrans
#define Ref_Vu0Cur_Init Vu0Cur_Init
#define Ref_Vu0Cur_InverseRT Vu0Cur_InverseRT
#define Ref_Vu0Cur_IsStackUsed Vu0Cur_IsStackUsed
#define Ref_Vu0Cur_LoadIdentity Vu0Cur_LoadIdentity
#define Ref_Vu0Cur_LoadIdentityRot Vu0Cur_LoadIdentityRot
#define Ref_Vu0Cur_LoadMtx Vu0Cur_LoadMtx
#define Ref_Vu0Cur_MulMtx Vu0Cur_MulMtx
#define Ref_Vu0Cur_MulMtxRev Vu0Cur_MulMtxRev
#define Ref_Vu0Cur_MulVec3 Vu0Cur_MulVec3
#define Ref_Vu0Cur_MulVec4 Vu0Cur_MulVec4
#define Ref_Vu0Cur_Pop Vu0Cur_Pop
#define Ref_Vu0Cur_PopN Vu0Cur_PopN
#define Ref_Vu0Cur_ProjectInt Vu0Cur_ProjectInt
#define Ref_Vu0Cur_ProjectPoint Vu0Cur_ProjectPoint
#define Ref_Vu0Cur_ProjectPoints Vu0Cur_ProjectPoints
#define Ref_Vu0Cur_ProjectPointsStq Vu0Cur_ProjectPointsStq
#define Ref_Vu0Cur_ProjectPointStq Vu0Cur_ProjectPointStq
#define Ref_Vu0Cur_Push Vu0Cur_Push
#define Ref_Vu0Cur_ResetStack Vu0Cur_ResetStack
#define Ref_Vu0Cur_RotateX Vu0Cur_RotateX
#define Ref_Vu0Cur_RotateXYZ Vu0Cur_RotateXYZ
#define Ref_Vu0Cur_RotateY Vu0Cur_RotateY
#define Ref_Vu0Cur_RotateYXZ Vu0Cur_RotateYXZ
#define Ref_Vu0Cur_RotateZ Vu0Cur_RotateZ
#define Ref_Vu0Cur_RotateZXY Vu0Cur_RotateZXY
#define Ref_Vu0Cur_RotateZXYTranslate Vu0Cur_RotateZXYTranslate
#define Ref_Vu0Cur_RotEulerMulVec3 Vu0Cur_RotEulerMulVec3
#define Ref_Vu0Cur_RotEulerMulVec4 Vu0Cur_RotEulerMulVec4
#define Ref_Vu0Cur_ScaleDiag Vu0Cur_ScaleDiag
#define Ref_Vu0Cur_ScaleDiagUniform Vu0Cur_ScaleDiagUniform
#define Ref_Vu0Cur_SetTrans Vu0Cur_SetTrans
#define Ref_Vu0Cur_StoreMtx Vu0Cur_StoreMtx
#define Ref_Vu0Cur_Translate Vu0Cur_Translate
#define Ref_Vu0Cur_TranslateLocal Vu0Cur_TranslateLocal
#define Ref_Vu0Cur_Transpose Vu0Cur_Transpose
#define Ref_Vu0_Init Vu0_Init
#define Ref_Vu0_InitAxisRegs Vu0_InitAxisRegs
#define Ref_Vu0_ResetState Vu0_ResetState
#define Ref_Vu0R_Init Vu0R_Init
#define Ref_Vu0R_Next Vu0R_Next
#define Ref_Vu0Screen_LoadMtx Vu0Screen_LoadMtx
#define Ref_Vu0Screen_SetMulMtx Vu0Screen_SetMulMtx
#define Ref_Vu0Screen_StoreMtx Vu0Screen_StoreMtx
#define Ref_Vu0_SinCos Vu0_SinCos
#define Ref_Vu0_Stub0 Vu0_Stub0
#define Ref_Vu0_Stub1 Vu0_Stub1
#define Ref_Vu0_Stub2 Vu0_Stub2
#define Ref_Vu0_Stub3 Vu0_Stub3
#define Ref_Vu0_Stub4 Vu0_Stub4
#define Ref_Vu0_Stub5 Vu0_Stub5
#define Ref_Vu0_Stub6 Vu0_Stub6
#define Ref_Vu0_Stub7 Vu0_Stub7
#define Ref_Vu0_Stub8 Vu0_Stub8
#define Ref_Vu0View_ApplyTransRot Vu0View_ApplyTransRot
#define Ref_Vu0View_LoadMtx Vu0View_LoadMtx
#define Ref_Vu0View_SetMulMtx Vu0View_SetMulMtx
#define Ref_Vu0View_SetRotTrans Vu0View_SetRotTrans
#define Ref_Vu0View_StoreMtx Vu0View_StoreMtx
#define Ref_StgVu_RotateX StgVu_RotateX
#define Ref_StgVu_RotateY StgVu_RotateY
#define Ref_StgVu_RotateZ StgVu_RotateZ
