name: Dragon Ball Z - Budokai Tenkaichi 3 (USA) - BIN/DBZP.BIN overlay
sha1: 4f910969e05d9b25c83af7642b60da9949a4348b
options:
  basename: DBZP
  target_path: disc/BIN/DBZP.BIN
  elf_path: build/DBZP.elf
  base_path: ..
  platform: ps2
  compiler: EEGCC

  # The overlay shares the main executable's $gp.
  gp_value: 0x00304270

  asm_path: asm/dbzp
  src_path: src/dbzp
  build_path: build
  data_path: data
  nonmatchings_path: nonmatchings

  ld_script_path: build/DBZP.ld
  ld_dependencies: True
  ld_wildcard_sections: True

  create_asm_dependencies: False
  generate_asm_macros_files: False

  find_file_boundaries: False

  o_as_suffix: True

  symbol_addrs_path:
    - config/symbol_addrs.txt
    - config/symbols/lib.txt
    - config/symbols/game.txt
    - config/symbols/sys_util.txt
    - config/symbols/sys_file.txt
    - config/symbols/rand_pool.txt
    - config/symbols/boot.txt
    - config/symbols/sys_pad.txt
    - config/symbols/sys_adx.txt
    - config/symbols/sys_common.txt
    - config/symbols/battle.txt
    - config/symbols/btl_seq.txt
    - config/symbols/game_pad.txt
    - config/symbols/save.txt
    - config/symbols/battle_work.txt
    - config/symbols/battle_setup.txt
    - config/symbols/btl_cam.txt
    - config/symbols/btl_input.txt
    - config/symbols/btl_scene.txt
    - config/symbols/btl_text.txt
    - config/symbols/fade.txt
    - config/symbols/gfx.txt
    - config/symbols/math3d.txt
    - config/symbols/snd.txt
    - config/symbols/btl_1bb.txt
    - config/symbols/btl_ai.txt
    - config/symbols/btl_char_api.txt
    - config/symbols/btl_char_cam.txt
    - config/symbols/btl_char_mgr.txt
    - config/symbols/btl_obj.txt
    - config/symbols/btl_replay.txt
    - config/symbols/btl_script.txt
    - config/symbols/movie.txt
    - config/symbols/sys_helpers.txt
    - config/symbols/sys_rigid.txt
    - config/symbols/btl_script_cmd.txt
    - config/symbols/btl_char_status.txt
    - config/symbols/btl_char_hit.txt
    - config/symbols/btl_char_coll.txt
    - config/symbols/btl_char_member.txt
    - config/symbols/btl_char_ctl.txt
    - config/symbols/btl_char_flag.txt
    - config/symbols/btl_char_move.txt
    - config/symbols/btl_char_action.txt
    - config/symbols/btl_ai_act.txt
    - config/symbols/btl_ai_think.txt
    - config/symbols/btl_char_fx.txt
    - config/symbols/btl_act_a.txt
    - config/symbols/btl_act_b.txt
    - config/symbols/btl_act_c.txt
    - config/symbols/btl_act_d.txt
    - config/symbols/btl_act_e.txt
    - config/symbols/btl_act_f.txt
    - config/symbols/btl_act_g.txt
    - config/symbols/btl_act_h.txt
    - config/symbols/btl_act_i.txt
    - config/symbols/btl_act_j.txt
    - config/symbols/btl_capi_a.txt
    - config/symbols/btl_capi_b.txt
    - config/symbols/btl_tech_a.txt
    - config/symbols/btl_tech_b.txt
    - config/symbols/eft_a.txt
    - config/symbols/eft_b.txt
    - config/symbols/eft_c.txt
    - config/symbols/eft_d.txt
    - config/symbols/eft_e.txt
    - config/symbols/eft_f.txt
    - config/symbols/eft_g.txt
    - config/symbols/eft_h.txt
    - config/symbols/eft_i.txt
    - config/symbols/eft_j.txt
    - config/symbols/eft_k.txt
    - config/symbols/eft_l.txt
    - config/symbols/eft_m.txt
    - config/symbols/stg_a.txt
    - config/symbols/stg_b.txt
    - config/symbols/stg_c.txt
    - config/symbols/eft_n.txt
    - config/symbols/eft_o.txt
    - config/symbols/eft_p.txt
    - config/symbols/eft_q.txt
    - config/symbols/eft_r.txt
    - config/symbols/eft_s.txt
    - config/symbols/eft_t.txt
    - config/symbols/eft_u.txt
    - config/symbols/eft_v.txt
    - config/symbols/eft_w.txt
    - config/symbols/eft_x.txt
    - config/symbols/eft_y.txt
    - config/symbols/eft_z.txt
    - config/symbols/eft_aa.txt
    - config/symbols/eft_ab.txt
    - config/symbols/eft_ac.txt
    - config/symbols/eft_ad.txt
    - config/symbols/eft_det_a.txt
    - config/symbols/eft_det_b.txt
    - config/symbols/stg_d.txt
    - config/symbols/col_a.txt
    - config/symbols/eft_ae.txt
    - config/symbols/col_b.txt
    - config/symbols/col_c.txt
    - config/symbols/bobj_a.txt
    - config/symbols/bobj_b.txt
    - config/symbols/btl_ai_seq_a.txt
    - config/symbol_addrs_dbzp.txt
  reloc_addrs_path:
    - config/reloc_addrs_dbzp.txt

  undefined_funcs_auto_path: build/dbzp_undefined_funcs_auto.txt
  undefined_syms_auto_path: build/dbzp_undefined_syms_auto.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  named_regs_for_c_funcs: False

segments:
  - name: dbzp
    type: code
    start: 0x000000
    vram: 0x00334C00
    subalign: null
    align: 4
    subsegments:
      - [0x000000, asm, "000000"]
      - [0x07C280, data, "07C280"]
  - [0x89B1C]
