name: Dragon Ball Z - Budokai Tenkaichi 3 (USA) (SLUS-21678)
sha1: caee6c2269bba89fc51eea9e7beac3adbec9dc52
options:
  basename: SLUS_216.78
  target_path: disc/SLUS_216.78.rom
  elf_path: build/SLUS_216.78.elf
  base_path: ..
  platform: ps2
  compiler: EEGCC

  gp_value: 0x00304270
  ld_gp_expression: cod_LIT4_START + 0x7FF0

  # asm_path: asm
  # src_path: src
  # build_path: build

  ld_script_path: build/SLUS_216.78.ld
  ld_dependencies: True
  ld_wildcard_sections: True
  ld_bss_contains_common: True

  create_asm_dependencies: False
  generate_asm_macros_files: False

  find_file_boundaries: False

  o_as_suffix: True

  symbol_addrs_path:
    - config/symbol_addrs.txt
    - config/symbols/lib.txt
    - config/symbols/game.txt
    - config/symbols/sys_util.txt
    - config/symbols/sys_file.txt
    - config/symbols/rand_pool.txt
    - config/symbols/boot.txt
    - config/symbols/sys_pad.txt
    - config/symbols/sys_adx.txt
    - config/symbols/sys_common.txt
    - config/symbols/battle.txt
    - config/symbols/btl_seq.txt
    - config/symbols/game_pad.txt
    - config/symbols/option.txt
  reloc_addrs_path:
    - config/reloc_addrs.txt

  undefined_funcs_auto_path: build/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  named_regs_for_c_funcs: False

  section_order:
    - .text
    # - .vutext
    # - .text_nop
    # - .ctors
    # - .dtors
    - .data
    # - .eh_frame
    - .rodata
    - .lit4
    - .sdata
    - .sbss
    # - .scommon
    - .bss

  auto_link_sections:
    # - .text_nop
    # - .ctors
    # - .dtors
    - .data
    # - .eh_frame
    - .rodata
    - .lit4
    - .sdata
    - .sbss
    # - .scommon
    - .bss

segments:
  - name: cod
    type: code
    start: 0x000000
    vram: 0x00100000
    bss_size: 0x359A8
    subalign: null
    align: 128
    subsegments:
      - [0x000000, asm, cod/000000] # .text
      - [0x000258, c, main]
      - [0x000670, c, sys/dma]
      - [0x001D40, asm, cod/001D40]
      - [0x022940, c, sys/pad]
      - [0x023130, asm, cod/023130]
      - [0x02B570, c, battle/battle]
      - [0x02BD58, asm, cod/02BD58]
      - [0x0A7018, c, battle/btl_pool]
      - [0x0A7608, asm, cod/0A7608]
      - [0x115540, c, battle/btl_seq]
      - [0x1187E0, asm, cod/1187E0]
      - [0x154A20, c, sys/rand]
      - [0x154E28, c, sys/heap]
      - [0x1557A8, c, sys/heap_info]
      - [0x155898, c, sys/list]
      - [0x155EE8, c, sys/queue]
      - [0x156128, c, sys/align]
      - [0x1562A8, asm, cod/1562A8]
      - [0x1574F0, c, sys/game_pad]
      - [0x157870, asm, cod/157870]
      - [0x163098, c, sys/debug]
      - [0x1630E8, c, sys/common]
      - [0x163278, c, sys/bpe]
      - [0x163478, c, sys/job]
      - [0x1635C8, c, sys/loading]
      - [0x164A50, c, sys/file]
      - [0x165578, c, sys/adx]
      - [0x166088, c, sys/option]
      - [0x166728, asm, cod/166728]
      - [0x173CA0, c, cri/adxt]
      - [0x173CF0, asm, cod/173CF0]
      - [0x1BF6B0, textbin, cod/1BF6B0] # .vutext
      - [0x1C3380, data, cod/1C3380] # .text_nop
      - [0x1C3388, data, cod/1C3388] # .ctors
      - [0x1C3398, data, cod/1C3398] # .dtors
      - [0x1C3400, data, cod/1C3400] # .data
      - [0x1EB358, data, cod/1EB358] # .eh_frame
      - [0x1EB380, rodata, cod/1EB380] # .rodata
      - [0x1EB3A8, .rodata, main]
      - [0x1EB550, .rodata, sys/dma]
      - [0x1EB5B0, rodata, cod/1EB5B0]
      - [0x1F1A80, .rodata, battle/btl_seq]
      - [0x1F1B30, rodata, cod/1F1B30]
      - [0x1F3500, .rodata, sys/file]
      # The original padded each object's .rodata to 16 bytes; ours pads to 8, so the last 8
      # bytes of file.c's padding are carried by the next assembly chunk.
      - [0x1F35A8, rodata, cod/1F35A8]
      - [0x1F4490, .rodata, cri/adxt]
      - [0x1F44C0, rodata, cod/1F44C0]
      - [0x1FC280, lit4, cod/1FC280] # .lit4
      - [0x1FE1C8, .lit4, battle/btl_seq]
      - [0x1FE1D8, lit4, cod/1FE1D8]
      - [0x1FE7B4, .lit4, sys/loading]
      - [0x1FE7C0, .lit4, sys/adx]
      - [0x1FE7C4, lit4, cod/1FE7C4]
      - [0x1FE880, sdata, cod/1FE880] # .sdata
      - { type: sbss, vram: 0x002FF180, name: cod/002FF180 } # .sbss
      - { type: bss, vram: 0x002FF280, name: cod/002FF280 } # .scommon
      - { type: bss, vram: 0x002FF300, name: cod/002FF300 } # .bss
  - [0x1FF180]
