#!/usr/bin/env python3
"""Makes port/src/gs/overlay_font.h, the settings overlay's font: ASCII 32..126 of a monospaced system font as 8-bit
coverage, one fixed cell per character. The header is committed, so the build does not need this tool or Pillow.
    python3 port/tools/gen_font.py [font.ttf] [pixel size]"""
import subprocess, sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

path = sys.argv[1] if len(sys.argv) > 1 else subprocess.run(["fc-match", "-f", "%{file}", "DejaVu Sans Mono"], capture_output=True, text=True).stdout
size = int(sys.argv[2]) if len(sys.argv) > 2 else 15
font = ImageFont.truetype(path, size)
asc, desc = font.getmetrics()
cw, ch = int(font.getlength("M") + 0.5), asc + desc
out = [f"/* Generated by port/tools/gen_font.py from {Path(path).name} at {size} px: do not edit. */",
       f"#define FONT_W {cw}", f"#define FONT_H {ch}", "static const unsigned char kFont[95][FONT_W * FONT_H] = {"]
for c in range(32, 127):
    im = Image.new("L", (cw, ch), 0)
    ImageDraw.Draw(im).text((0, 0), chr(c), font=font, fill=255)
    out.append("    {" + ",".join(str(v) for v in im.tobytes()) + "},")
out.append("};")
(Path(__file__).resolve().parents[1] / "src/gs/overlay_font.h").write_text("\n".join(out) + "\n")
print(f"cell {cw} x {ch}")
