#!/usr/bin/env python3
"""First link of the PC build: every object from undefined.py, plus generated stubs for whatever is still missing.
A stub prints its name and stops the program, so running the result shows what the game needs first.
Usage: port/tools/undefined.py && port/tools/link.py     -> port/build/bt3"""
import pathlib, re, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
B = ROOT / "port/build"
HOST = set("acosf asinf atan2f atanf atoi cosf malloc memcpy memset powf rand sinf sprintf sqrtf srand strcmp strcpy "
           "strlen tanf sincosf __udivdi3 __umoddi3 free memmove strncpy strcat strncmp memcmp printf abs exit fabsf floorf ceilf fmodf sqrt sin cos atan2 pow floor qsort strchr strrchr strstr "
           "vsprintf sscanf toupper tolower labs log logf expf log10f fabs".split())

def nm(objs):
    out = subprocess.run(["nm", "-A"] + objs, capture_output=True, text=True).stdout
    und, dfn = set(), set()
    for l in out.splitlines():
        m = re.match(r"\S+:\s*[0-9a-f]*\s+(\w)\s+(\S+)$", l)
        if m:
            (und if m.group(1) == "U" else dfn).add(m.group(2)) if m.group(1) == "U" or m.group(1).isupper() else None
    return und, dfn

def main():
    objs = [str(o) for o in sorted((B / "obj").glob("*.o")) + sorted((B / "obj_data").glob("*.o"))]
    und, dfn = nm(objs)
    need = sorted(s for s in und - dfn - HOST if not s.startswith("_GLOBAL"))
    lines = ['/* Generated by port/tools/link.py: one stub per symbol the PC build does not provide yet. */',
             'extern int printf(const char *, ...);', 'extern void exit(int);',
             'static void missing(const char *n) { printf("bt3: not implemented yet: %s\\n", n); exit(3); }']
    lines += [f'void {s}(void) {{ missing("{s}"); }}' for s in need]
    (B / "gen").mkdir(exist_ok=True)
    (B / "gen/stubs.c").write_text("\n".join(lines) + "\n")
    r = subprocess.run(["gcc", "-m32", "-no-pie", "-w", "-o", str(B / "bt3"), str(B / "gen/stubs.c")] + objs +
                       ["-lm", "-Wl,--allow-multiple-definition" if "--force" in sys.argv else "-Wl,--warn-common"],
                       capture_output=True, text=True)
    errs = [l for l in r.stderr.splitlines() if "multiple definition" in l or "undefined reference" in l or "rror" in l]
    print(f"{len(need)} stubs; link {'OK -> port/build/bt3' if r.returncode == 0 else 'FAILED'}; {len(errs)} error lines")
    (B / "link.err").write_text(r.stderr)
    for l in errs[:12]:
        print("  " + l[-160:])

main()
