#!/usr/bin/env python3
"""Links the PC build: every object from undefined.py, plus generated stubs for whatever is still missing.
A stub prints its name and stops the program, so running the result shows what the game needs next.
Usage: port/tools/undefined.py && port/tools/link.py     -> port/build/bt3"""
import os, pathlib, re, subprocess

ROOT = pathlib.Path(__file__).resolve().parents[2]
B = ROOT / "port/build"
VARIANT = os.environ.get("BT3_CC", "gcc")  # see undefined.py
OBJ = "obj" if VARIANT == "gcc" else "obj_" + VARIANT
EXE = "bt3" if VARIANT == "gcc" else "bt3_" + VARIANT

def link(objs, extra):
    return subprocess.run(["gcc", "-m32", "-no-pie", "-w", "-o", str(B / EXE)] + extra + objs +
                          ["-lstdc++", "-lm", "-lpthread", "-lSDL3", "-Wl,--defsym=D_3BE71C=0x3BE71C", "-Wl,--wrap=Progress_Main", "-rdynamic"], capture_output=True, text=True)

def main():
    objs = [str(o) for o in sorted((B / OBJ).glob("*.o")) + sorted((B / "obj_data").glob("*.o"))]
    r = link(objs, [])  # first pass: ask the linker what nobody provides (the host C library included)
    need = sorted(set(re.findall(r"undefined reference to `(\w+)'", r.stderr)))
    lines = ['/* Generated by port/tools/link.py: one stub per symbol the PC build does not provide yet. */',
             'extern int printf(const char *, ...);', 'extern void exit(int);',
             'static void missing(const char *n) { printf("bt3: not implemented yet: %s\\n", n); exit(3); }']
    lines += [f'void {s}(void) {{ missing("{s}"); }}' for s in need]
    (B / "gen").mkdir(exist_ok=True)
    (B / "gen/stubs.c").write_text("\n".join(lines) + "\n")
    (B / "stubs.txt").write_text("\n".join(need) + "\n")
    r = link(objs, [str(B / "gen/stubs.c")])
    errs = [l for l in r.stderr.splitlines() if "multiple definition" in l or "undefined reference" in l or "rror" in l]
    print(f"{len(need)} stubs; link {'OK -> port/build/' + EXE if r.returncode == 0 else 'FAILED'}; {len(errs)} error lines")
    for l in errs[:12]:
        print("  " + l[-160:])

main()
